#!/bin/bash
# -p print out number instead of copying to clipboard

if [[ "$1" == "-p" ]]; then
  xsel --clipboard --output | tr -d ' ' | sed '$ ! s/$/+/' | tr -d '\n' | xargs -I % python3 -c "print(str(round(%, 2)))"
else
  xsel --clipboard --output | tr -d ' ' | sed '$ ! s/$/+/' | tr -d '\n' | xargs -I % python3 -c "print(str('{0:.2f}'.format(round(%, 2))))" | tr -d '\n' | xsel --clipboard --input
fi
