#!/bin/bash

points=0

if [ ! -f ~/.times_high_score ]; then
  echo "0" > ~/.times_high_score
  high_score=0
else
  high_score=$(cat ~/.times_high_score)
fi

for i in {1..10}
do
  rone=$(( $RANDOM % 7 + 3 )) # 3-9
  rtwo=$(( $RANDOM % 7 + 3 )) # 3-9
  answ=$(($rone * $rtwo))
  echo "$rone x $rtwo"
  read user_input

  if [ "$user_input" == "$answ" ]; then
    echo "Correct!"
    points=$(($points + 10))
  else
    echo "Actually, it's $answ!"
    points=$(($points - 10))
  fi
done

score=$(($points - $SECONDS))

if [ $score -gt $high_score ]; then
  high_score=$score
  echo "$high_score" > ~/.times_high_score
  echo "You set a new high score of $high_score"
fi

echo "Your score is $score. The High score is $high_score"
