#!/bin/bash

#Config options:

#This is the name of your virtual machine and the name that appears in the hosts file.
vmname=dev-kwerklund
hostsname=$vmname

#Fetching ip address with virtualbox's guestproperties - must install guest additions
neweth0=$(VBoxManage guestproperty get $vmname "/VirtualBox/GuestInfo/Net/0/V4/IP")
neweth1=$(VBoxManage guestproperty get $vmname "/VirtualBox/GuestInfo/Net/1/V4/IP")
if [ "$neweth0" == "No value set!" ] || [ "$neweth1" == "No value set!" ]; then

  # When we fail to fetch IP address, get it from the user.
  echo "One, or both of the IP addresses isn't set up"
  echo "This my be due to not having guest additions installed."
  echo "OR, it may be because your virtual box isn't running."
  echo "Obtaining ip through meatspace..."

  while true; do
    echo -e "Enter IP for eth0:"
    read neweth0
    
    read -p "Eth0: $neweth0. Is this correct? [y|n] " -n 1
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      break
    fi
  done

  echo -e "\n"

  while true; do
    echo -e "Enter IP for eth1:"
    read neweth1
    
    read -p "Eth1: $neweth1. Is this correct? [y|n] " -n 1
    if [[ $REPLY =~ ^[Yy]$ ]]; then
      break
    fi
  done

  echo -e "\n"
else

  neweth0=$(echo $neweth0 | awk '{print $2}')
  neweth1=$(echo $neweth1 | awk '{print $2}')

fi

#Check with user before running changes:
echo -e "Writing to hosts file:\nEth0: $neweth0\nEth1: $neweth1"
read -p "Make this change? [y|n] " yn
if [[ ! $yn =~ ^[Yy]$ ]]; then
  echo "Didn't change anything."
  exit 0
fi


#eth0 search & replace:
sudo sed -i.bak "s/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\ \{4\}$hostsname/$neweth0\ \ \ \ $hostsname/g" /etc/hosts
sudo sed -i.bak "s/^[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\ \{4\}secure-$hostsname/$neweth0\ \ \ \ secure-$hostsname/g" /etc/hosts


#eth1 search & replace:
sudo sed -i.bak s/^\n*.*$hostsname\.istockimg\.com/$neweth1\ \ \ \ $hostsname\.istockimg\.com/g /etc/hosts
#sudo sed -i.bak s/^\n*.*$hostsname\.istockimg\.com/$neweth1\ \ \ \ $hostsname\.istockimg\.com/g /etc/hosts
#sudo sed -i.bak s/^\n*.*.$hostsname.istockimg.com/$eth1    $hostsname.istockimg.com/g /etc/hosts

